---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: approver
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - installplans
      - subscriptions
    verbs:
      - get
      - list
      - patch
