---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: installplan-approver-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: approver
subjects:
  - kind: ServiceAccount
    name: approver-sa
