---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# RBAC resources
  - rbac/serviceaccount.yaml
  - rbac/role.yaml
  - rbac/rolebinding.yaml
# Approver job
  - job/approver.yaml
